version: '3.3'

services:
  database:
    image: postgres
    volumes:
      - ./log-directory:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1488
      POSTGRES_DB: apartments
      POSTGRES_HOST_AUTH_METHOD: trust
  app:
    build: .
    container_name: app
    command: bash -c "uvicorn main:api --port=8000 --host=0.0.0.0 --reload"
    expose:
      - 8000
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - database

volumes:
  postgres: